version: '3'

services:
  postgres-compose:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "Postgres2019!"
    ports:
      - "15432:5432"
    volumes:
      - ./data:/data/db
    networks:
      - postgres-compose-network

  api:
    container_name: api-book-container
    build: .
    image: node:16
    working_dir: /usr/src/node-api
    command: bash -c "npm install --only=prod && npx typeorm migration:run && npm start"
    environment:
      - PG_DB_TYPE=postgres
      - PG_DB_HOST=postgres-compose
      - PG_DB_PORT=5432
      - PG_DB_USERNAME=postgres
      - PG_DB_PASSWORD=Postgres2019!
      - PG_DB_BASE=postgres
      - API_PORT=5050
    volumes:
      - ./dist/:/usr/src/node-api/dist/
      - ./package.json:/usr/src/node-api/package.json
      - ./ormconfig.js:/usr/src/node-api/ormconfig.js
    ports:
      - "5050:5050"
    depends_on:
      - postgres-compose
    networks:
      - postgres-compose-network
    links:
      - postgres-compose

networks:
  postgres-compose-network:
    driver: bridge
