version: '3'

services:
  postgres-compose:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "Postgres2019!"
    ports:
      - "15432:5432"
    volumes:
      - ./data:/data/db
    networks:
      - postgres-compose-network
  api:
    container_name: api-book-container
    build: .
    image: book-node
    command: bash -c "npx typeorm migration:run && npm start"
    environment:
      - PG_DB_TYPE=postgres
      - PG_DB_HOST=postgres-compose
      - PG_DB_PORT=5432
      - PG_DB_USERNAME=postgres
      - PG_DB_PASSWORD=Postgres2019!
      - PG_DB_BASE=postgres
      - API_PORT=5050
    ports:
      - "5050:5050"
    depends_on:
      - postgres-compose
    networks:
      - postgres-compose-network
    links:
      - postgres-compose

networks:
  postgres-compose-network:
    driver: bridge
